/* 
 * UiPath.WebApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PropertyChanged;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = UiPathEJC.Service.Rest.Client.SwaggerDateConverter;

namespace UiPathEJC.Service.Rest.Model
{
    /// <summary>
    /// ConnectionData
    /// </summary>
    [DataContract]
    [ImplementPropertyChanged]
    public partial class ConnectionData :  IEquatable<ConnectionData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionData" /> class.
        /// </summary>
        /// <param name="LicenseKey">LicenseKey.</param>
        /// <param name="OrchestratorUrl">OrchestratorUrl.</param>
        public ConnectionData(string LicenseKey = default(string), string OrchestratorUrl = default(string))
        {
            this.LicenseKey = LicenseKey;
            this.OrchestratorUrl = OrchestratorUrl;
        }
        
        /// <summary>
        /// Gets or Sets LicenseKey
        /// </summary>
        [DataMember(Name="licenseKey", EmitDefaultValue=false)]
        public string LicenseKey { get; set; }

        /// <summary>
        /// Gets or Sets OrchestratorUrl
        /// </summary>
        [DataMember(Name="orchestratorUrl", EmitDefaultValue=false)]
        public string OrchestratorUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConnectionData {\n");
            sb.Append("  LicenseKey: ").Append(LicenseKey).Append("\n");
            sb.Append("  OrchestratorUrl: ").Append(OrchestratorUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConnectionData);
        }

        /// <summary>
        /// Returns true if ConnectionData instances are equal
        /// </summary>
        /// <param name="input">Instance of ConnectionData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConnectionData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LicenseKey == input.LicenseKey ||
                    (this.LicenseKey != null &&
                    this.LicenseKey.Equals(input.LicenseKey))
                ) && 
                (
                    this.OrchestratorUrl == input.OrchestratorUrl ||
                    (this.OrchestratorUrl != null &&
                    this.OrchestratorUrl.Equals(input.OrchestratorUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LicenseKey != null)
                    hashCode = hashCode * 59 + this.LicenseKey.GetHashCode();
                if (this.OrchestratorUrl != null)
                    hashCode = hashCode * 59 + this.OrchestratorUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// Property changed event handler
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Trigger when a property changed
        /// </summary>
        /// <param name="propertyName">Property Name</param>
        public virtual void OnPropertyChanged(string propertyName)
        {
            // NOTE: property changed is handled via "code weaving" using Fody.
            // Properties with setters are modified at compile time to notify of changes.
            var propertyChanged = PropertyChanged;
            if (propertyChanged != null)
            {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
