/* 
 * UiPath.WebApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PropertyChanged;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = UiPathEJC.Service.Rest.Client.SwaggerDateConverter;

namespace UiPathEJC.Service.Rest.Model
{
    /// <summary>
    /// HeartbeatPayload
    /// </summary>
    [DataContract]
    [ImplementPropertyChanged]
    public partial class HeartbeatPayload :  IEquatable<HeartbeatPayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeartbeatPayload" /> class.
        /// </summary>
        /// <param name="Heartbeats">Heartbeats.</param>
        /// <param name="ServiceUserName">ServiceUserName.</param>
        public HeartbeatPayload(List<HeartbeatDto> Heartbeats = default(List<HeartbeatDto>), string ServiceUserName = default(string))
        {
            this.Heartbeats = Heartbeats;
            this.ServiceUserName = ServiceUserName;
        }
        
        /// <summary>
        /// Gets or Sets Heartbeats
        /// </summary>
        [DataMember(Name="heartbeats", EmitDefaultValue=false)]
        public List<HeartbeatDto> Heartbeats { get; set; }

        /// <summary>
        /// Gets or Sets ServiceUserName
        /// </summary>
        [DataMember(Name="serviceUserName", EmitDefaultValue=false)]
        public string ServiceUserName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HeartbeatPayload {\n");
            sb.Append("  Heartbeats: ").Append(Heartbeats).Append("\n");
            sb.Append("  ServiceUserName: ").Append(ServiceUserName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HeartbeatPayload);
        }

        /// <summary>
        /// Returns true if HeartbeatPayload instances are equal
        /// </summary>
        /// <param name="input">Instance of HeartbeatPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HeartbeatPayload input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Heartbeats == input.Heartbeats ||
                    this.Heartbeats != null &&
                    this.Heartbeats.SequenceEqual(input.Heartbeats)
                ) && 
                (
                    this.ServiceUserName == input.ServiceUserName ||
                    (this.ServiceUserName != null &&
                    this.ServiceUserName.Equals(input.ServiceUserName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Heartbeats != null)
                    hashCode = hashCode * 59 + this.Heartbeats.GetHashCode();
                if (this.ServiceUserName != null)
                    hashCode = hashCode * 59 + this.ServiceUserName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// Property changed event handler
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Trigger when a property changed
        /// </summary>
        /// <param name="propertyName">Property Name</param>
        public virtual void OnPropertyChanged(string propertyName)
        {
            // NOTE: property changed is handled via "code weaving" using Fody.
            // Properties with setters are modified at compile time to notify of changes.
            var propertyChanged = PropertyChanged;
            if (propertyChanged != null)
            {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
