/* 
 * UiPath.WebApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PropertyChanged;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = UiPathEJC.Service.Rest.Client.SwaggerDateConverter;

namespace UiPathEJC.Service.Rest.Model
{
    /// <summary>
    /// Stores information about an application permission and role association.
    /// </summary>
    [DataContract]
    [ImplementPropertyChanged]
    public partial class PermissionDto :  IEquatable<PermissionDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionDto" /> class.
        /// </summary>
        /// <param name="Name">The name of the application permission..</param>
        /// <param name="IsGranted">States if a user associated with the role will be allowed or denied to perform the actions governed by the permission..</param>
        /// <param name="RoleId">The Id of the role associated with the permission..</param>
        /// <param name="Id">Id.</param>
        public PermissionDto(string Name = default(string), bool? IsGranted = default(bool?), int? RoleId = default(int?), long? Id = default(long?))
        {
            this.Name = Name;
            this.IsGranted = IsGranted;
            this.RoleId = RoleId;
            this.Id = Id;
        }
        
        /// <summary>
        /// The name of the application permission.
        /// </summary>
        /// <value>The name of the application permission.</value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// States if a user associated with the role will be allowed or denied to perform the actions governed by the permission.
        /// </summary>
        /// <value>States if a user associated with the role will be allowed or denied to perform the actions governed by the permission.</value>
        [DataMember(Name="IsGranted", EmitDefaultValue=false)]
        public bool? IsGranted { get; set; }

        /// <summary>
        /// The Id of the role associated with the permission.
        /// </summary>
        /// <value>The Id of the role associated with the permission.</value>
        [DataMember(Name="RoleId", EmitDefaultValue=false)]
        public int? RoleId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PermissionDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsGranted: ").Append(IsGranted).Append("\n");
            sb.Append("  RoleId: ").Append(RoleId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PermissionDto);
        }

        /// <summary>
        /// Returns true if PermissionDto instances are equal
        /// </summary>
        /// <param name="input">Instance of PermissionDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PermissionDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.IsGranted == input.IsGranted ||
                    (this.IsGranted != null &&
                    this.IsGranted.Equals(input.IsGranted))
                ) && 
                (
                    this.RoleId == input.RoleId ||
                    (this.RoleId != null &&
                    this.RoleId.Equals(input.RoleId))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.IsGranted != null)
                    hashCode = hashCode * 59 + this.IsGranted.GetHashCode();
                if (this.RoleId != null)
                    hashCode = hashCode * 59 + this.RoleId.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// Property changed event handler
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Trigger when a property changed
        /// </summary>
        /// <param name="propertyName">Property Name</param>
        public virtual void OnPropertyChanged(string propertyName)
        {
            // NOTE: property changed is handled via "code weaving" using Fody.
            // Properties with setters are modified at compile time to notify of changes.
            var propertyChanged = PropertyChanged;
            if (propertyChanged != null)
            {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
